<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>JSON-tmLanguage</string>
	</array>
	<key>name</key>
	<string>Sublime Text Syntax Definition</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.json-tmlanguage</string>
	<key>uuid</key>
	<string>8c7e3a99-1780-4b72-9ce5-585949c0563e</string>
</dict>
</plist>
