<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sublime-keymap</string>
	</array>
	<key>name</key>
	<string>Sublime Text Key Map</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.start.sublimekeymap</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.sublimekeymap</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.keymap.array.sublimekeymap</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dictionary</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.sublimekeymap</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>dictionary</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.start.sublimekeymap</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.sublimekeymap</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.keymap.dictionary.sublimekeymap</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublimekeymap</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.keybinding.attached.command.sublimekeymap</string>
						</dict>
					</dict>
					<key>match</key>
					<string>"(command)"(:)\s+"([a-zA-Z0-9_]+)"</string>
					<key>name</key>
					<string>meta.keybinding.command.definition.sublimekeymap</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"(keys)":\s+(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublimekeymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.sequence.start.sublimekeymap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.sequence.end.sublimekeymap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.keybinding.sequence.sublimekeymap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.constant</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?:(ctrl|shift|alt|super)\+)|(spacebar|backquote|enter|f\d{1,2}|[a-z,;.:-_])</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"(args)":\s+(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublimekeymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.sequence.start.sublimekeymap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.sequence.end.sublimekeymap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.keybinding.command.arguments.sublimekeymap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.sublimekeymap</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.constant</string>
								</dict>
							</dict>
							<key>match</key>
							<string>"([a-z0-9_]+)"\s*(:)\s*"([a-z]+)"</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.sublimekeymap</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
							</dict>
							<key>match</key>
							<string>"([a-z0-9_]+)"\s*(:)\s*(false|true|\d+)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"(context)":\s+(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublimekeymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.sequence.start.sublimekeymap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.sequence.end.sublimekeymap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.keybinding.context.sublimekeymap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.sublimekeymap</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.constant</string>
								</dict>
							</dict>
							<key>match</key>
							<string>"([a-z0-9_]+)"\s*(:)\s*"([a-z]+)"</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.sublimekeymap</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
							</dict>
							<key>match</key>
							<string>"([a-z0-9_]+)"\s*(:)\s*(false|true|\d+)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sublimekeymap</string>
	<key>uuid</key>
	<string>23ab842c-187a-41f8-b0aa-40d43c0ba7fe</string>
</dict>
</plist>
