<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sublime-build</string>
	</array>
	<key>name</key>
	<string>Sublime Text Build System</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.definition.build-system</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fileRegex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>command</key>
		<dict>
			<key>begin</key>
			<string>"(cmd)"\s*:</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[</string>
					<key>name</key>
					<string>punctuation.definition.arg.list.end.sublimebuild</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#genericArray</string>
				</dict>
			</array>
		</dict>
		<key>fileRegex</key>
		<dict>
		</dict>
		<key>genericArray</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.definition.array.generic.sublimebuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\d\.]+</string>
					<key>name</key>
					<string>constant.numeric.sublimebuild</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#genericArray</string>
				</dict>
			</array>
		</dict>
		<key>selector</key>
		<dict>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.sublimebuild</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\(?:"|t|n|r))</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.sublimebuild</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sublimebuild</string>
	<key>uuid</key>
	<string>22a1eed4-8670-460c-91e5-682aa6661180</string>
</dict>
</plist>
