<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sublime-keymap</string>
	</array>
	<key>name</key>
	<string>Sublime Text Key Map</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.keybindings.start.sublime-keymap</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.keybindings.end.sublime-keymap</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.array.keybindings.sublime-keymap</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyBinding</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.sublime-keymap</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#theRest</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>context</key>
		<dict>
			<key>begin</key>
			<string>\{\s*"(key)"(:)\s*"(num_selections|overlay_visible)"</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.sublime-keymap</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.constant.keybinding.context.operand.left.sublime-keymap</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.keybinding.context.sublime-keymap</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublime-keymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.constant.keybinding.context.operator.name.sublime-keymap</string>
						</dict>
					</dict>
					<key>match</key>
					<string>"(operator)":\s*"(equal|not_equal)"</string>
					<key>name</key>
					<string>meta.keybinding.context.operator.sublime-keymap</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublime-keymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.constant.keybinding.context.operand.right.sublime-keymap</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.keybinding.context.operand.right.constant.sublime-keymap</string>
						</dict>
					</dict>
					<key>match</key>
					<string>"(operand)":\s*((true|false|\d+)|"[ a-zA-Z0-9_]+")</string>
					<key>name</key>
					<string>meta.keybinding.operand.sublime-keymap</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#theRest</string>
				</dict>
			</array>
		</dict>
		<key>keyBinding</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.keybinding.definition.start.sublime-keymap</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.keybinding.definition.end.sublime-keymap</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.keybinding.definition.sublime-keymap</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublime-keymap</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.keybinding.command.name.sublime-keymap</string>
						</dict>
					</dict>
					<key>match</key>
					<string>"(command)"(:)\s+"([a-zA-Z0-9_]+)"</string>
					<key>name</key>
					<string>meta.keybinding.command.sublime-keymap</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"(keys)":\s+(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublime-keymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.key.sequence.start.sublime-keymap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.key.sequence.end.sublime-keymap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.keybinding.array.key.sequence.sublime-keymap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.keybinding.key.sequence.key.modifier.sublime-keymap</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keybinding.key.sequence.key.modifier.suffix.sublime-keymap</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.constant.keybinding.key.sequence.key.sublime-keymap</string>
								</dict>
							</dict>
							<key>match</key>
							<string>"(?:(ctrl|shift|alt|super)(\+))|(spacebar|backquote|enter|f\d{1,2}|[a-z,;.:-_]+)"</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"(args)":\s+(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublime-keymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.command.arguments.start.sublime-keymap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keybinding.command.arguments.end.sublime-keymap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.keybinding.command.arguments.sublime-keymap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.keybinding.command.parameter.name.sublime-keymap</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.constant.keybinding.command.parameter.value.sublime-keymap</string>
								</dict>
							</dict>
							<key>match</key>
							<string>"([a-z0-9_]+)"\s*(:)\s*"([ a-zA-Z\./-]+)"</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.keybinding.command.parameter.name.sublime-keymap</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.command.parameter.value.constant.sublime-keymap</string>
								</dict>
							</dict>
							<key>match</key>
							<string>"([a-z0-9_]+)"\s*(:)\s*(false|true|\d+)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#theRest</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"(context)":\s+(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.sublime-keymap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.keybinding.array.contexts.start.sublime-keymap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.keybinding.array.contexts.end.sublime-keymap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.keybinding.array.contexts.sublime-keymap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#context</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#theRest</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#theRest</string>
				</dict>
			</array>
		</dict>
		<key>theRest</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=,),</string>
					<key>name</key>
					<string>invalid.illegal.sublime-keymap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,\s*(?=\s*\},?\s*$)</string>
					<key>name</key>
					<string>invalid.illegal.sublime-keymap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.sublime-keymap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s]</string>
					<key>name</key>
					<string>invalid.illegal.sublime-keymap</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sublime-keymap</string>
	<key>uuid</key>
	<string>23ab842c-187a-41f8-b0aa-40d43c0ba7fe</string>
</dict>
</plist>
