<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sublime-mousemap</string>
	</array>
	<key>name</key>
	<string>Sublime Text Mouse Map</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#multiLineComment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lineComment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\[)</string>
			<key>contentName</key>
			<string>meta.mousebinding.collection.sublimemousemap</string>
			<key>end</key>
			<string>(^\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#multiLineComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#button</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mainKeys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#supportKeys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numericPrimitives</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>button</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sublimemousemap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.button.mouse.sublimemousemap</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.double.quote.button.mouse.sublimemousemap</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)
  "(button)":
  \s*
  "(?:(button[1-5]|scroll_(?:down|up))|(\w*))"
</string>
		</dict>
		<key>lineComment</key>
		<dict>
			<key>match</key>
			<string>//.*?$</string>
			<key>name</key>
			<string>comment.line.double-slash.sublimemousemap</string>
		</dict>
		<key>mainKeys</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sublimemousemap</string>
				</dict>
			</dict>
			<key>match</key>
			<string>"(command|args|press_command|press_args|button|count)":</string>
		</dict>
		<key>modifier</key>
		<dict>
			<key>begin</key>
			<string>"(modifiers)":\s*\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sublimemousemap</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.mousebinding.definition.key.sequence.start.sublimemousemap</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.key.sequence.sublimemousemap</string>
					<key>end</key>
					<string>(")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.mousebinding.definition.key.sequence.end.sublimemousemap</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.modifier.key.sublimemousemap</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(shift|ctrl|alt|super|button[1-5])</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.modifier.key.sublimemousemap</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\w+)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#multiLineComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineComment</string>
				</dict>
			</array>
		</dict>
		<key>multiLineComment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.sublimemousemap</string>
		</dict>
		<key>numericPrimitives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:true|false)\b</string>
					<key>name</key>
					<string>constant.numeric.boolean.sublimemousemap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+(?:\.\d+)?</string>
					<key>name</key>
					<string>constant.numeric.sublimemousemap</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>contentName</key>
			<string>string.double.quote.sublimemousemap</string>
			<key>end</key>
			<string>"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.sublimemousemap</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.sublimesnippetraw</string>
				</dict>
			</array>
		</dict>
		<key>supportKeys</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.sublimemousemap</string>
				</dict>
			</dict>
			<key>match</key>
			<string>"([A-z]+?)":</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sublimemousemap</string>
	<key>uuid</key>
	<string>4df15ed4-7b42-41e2-849d-14347b8a3816</string>
</dict>
</plist>
