<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Sublime Text Snippet (Raw)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.block.start.sublimesnippetraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.storage.name.sublimesnippetraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sublimesnippetraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (\$)
(PARAM(\d)|USER_NAME|SELECTION
 |TM_(?&gt;CURRENT_LINE|CURRENT_WORD|FILENAME|FILEPATH|FULLNAME
      |LINE_INDEX|LINE_NUMBER|SELECTED_TEXT|SOFT_TABS|TAB_SIZE)
 )
</string>
			<key>name</key>
			<string>entity.other.attribute-name.environment.sublimesnippetraw</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.block.start.sublimesnippetraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.name.sublimesnippetraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)(\d+)</string>
			<key>name</key>
			<string>variable.field.numbered.sublimesnippetraw</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x) (\$)\{
(?:(\d+)
 |(PARAM(\d)|USER_NAME|SELECTION
   |TM_(?&gt;CURRENT_LINE|CURRENT_WORD|FILENAME|FILEPATH|FULLNAME
        |LINE_INDEX|LINE_NUMBER|SELECTED_TEXT|SOFT_TABS|TAB_SIZE))
 |(packages)
 |([a-zA-Z0-9_]+)
 )(/)
</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.block.start.sublimesnippetraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sublimesnippetraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.storage.name.sublimesnippetraw</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sublimesnippetraw</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.variable.storage.known-name.sublimesnippetraw</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.variable.storage.name.sublimesnippetraw</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.other.regex.start.sublimesnippetraw</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.sublimesnippetraw</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.definition.substitution.sublimesnippetraw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.regex.mid.sublimesnippetraw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>/([gim]*)(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.regex.end.sublimesnippetraw</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.regex-modifier.sublimesnippetraw</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\\d+</string>
							<key>name</key>
							<string>variable.other.regex.replace.sublimesnippetraw</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.other.escape.regex.replace.sublimesnippetraw</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.block.start.sublimesnippetraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.variable.storage.known-name.sublimesnippetraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.variable.storage.name.sublimesnippetraw</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.sublimesnippetraw</string>
			<key>match</key>
			<string>(\$)(?:(packages)|([a-zA-Z0-9_]+))</string>
			<key>name</key>
			<string>variable.field.sublimesnippetraw</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$)\{(\d+)(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.block.start.sublimesnippetraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sublimesnippetraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.block.definiton.sublimesnippetraw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.definition.variable.complex.sublimesnippetraw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sublimesnippetraw</string>
	<key>uuid</key>
	<string>9c9f9b3c-0e97-4423-a995-14d6412613d3</string>
</dict>
</plist>
