<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>YAML-tmTheme</string>
	</array>
	<key>name</key>
	<string>Sublime Text Colour Scheme Def (YAML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#yaml-tab-error</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#yaml-doc-start</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#yaml-doc-end</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#name-main</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#author</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#colorSpaceName</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#semanticClass</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-from-key</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#uuid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#gutterSettings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#gutterFormatting</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#settings-main</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#settings-default</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#name-scope</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scope</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#settings-scope</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#formatting-colour</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#formatting-style</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#formatting-font</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>author</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(author)(\2))(:) +((["']?).*?(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.author.yaml-tmtheme</string>
		</dict>
		<key>colorSpaceName</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(colorSpaceName)(\2))(:) +((["']?).*?(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.colorSpaceName.yaml-tmtheme</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)((#).*)</string>
		</dict>
		<key>comment-from-key</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^( *)(?:- +)?((["']?)(comment)(\3))(:) +([|&gt;])(?=, |,$| +#| *$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.comment-from-key.yaml-tmtheme</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmtheme</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.block.yaml-tmtheme</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>block
comment
</string>
					<key>contentName</key>
					<string>comment.block.from-key.block.yaml-tmtheme</string>
					<key>end</key>
					<string>^(?! *$|\1 )</string>
					<key>name</key>
					<string>meta.comment-from-key.block.yaml-tmtheme</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^ *|^ *- +)((["']?)(comment)(\2))(:) +(?!#)(["'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.comment-from-key.yaml-tmtheme</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmtheme</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>test comment over multiple lines?</string>
					<key>contentName</key>
					<string>comment.block.from-key.quoted.yaml-tmtheme</string>
					<key>end</key>
					<string>(?&lt;![^\\]\\)(\6)(?=, |,$| +#| *$| *})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.comment-from-key.quoted.yaml-tmtheme</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^( *)(?:-( +))?((["']?)(comment)(\4))(:)[ ]</string>
					<key>beginCaptures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.comment-from-key.yaml-tmtheme</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmtheme</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmtheme</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>this is a "test" comment in another line</string>
					<key>contentName</key>
					<string>comment.block.from-key.unquoted.yaml-tmtheme</string>
					<key>end</key>
					<string>^(?! *$|\1\2  )</string>
					<key>name</key>
					<string>meta.comment-from-key.unquoted.yaml-tmtheme</string>
				</dict>
			</array>
		</dict>
		<key>formatting-colour</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.other.yaml-tmtheme</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)    (activeGuide|background|bracketContentsForeground|bracketsForeground|caret|findHighlight|findHighlightForeground|foreground|invisibles|lineHighlight|selection|selectionBorder)(\2))(:) +((["']?)(#)([0-9a-fA-F]{6}[0-9a-fA-F]{2}?)(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.formatting.colour.yaml-tmtheme</string>
		</dict>
		<key>formatting-font</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)    (fontStyle)(\2))(:)(( | underline| bold| italic)+)(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.formatting.style.yaml-tmtheme</string>
		</dict>
		<key>formatting-style</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)    (bracketsOptions|tagsOptions|bracketContentsOptions)(\2))(:) +(underline|stippled_underline)(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.formatting.style.yaml-tmtheme</string>
		</dict>
		<key>gutterFormatting</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.other.yaml-tmtheme</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)  (background|foreground|divider)(\2))(:) +((["']?)(#)([0-9a-fA-F]{6})(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.colorSpaceName.yaml-tmtheme</string>
		</dict>
		<key>gutterSettings</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.settings.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(gutterSettings)(\2))(:)</string>
			<key>name</key>
			<string>meta.gutterSettings.yaml-tmtheme</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.yaml-tmtheme</string>
		</dict>
		<key>name-main</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.name.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(name)(\2))(:) +((["']?).*?(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.name-main.yaml-tmtheme</string>
		</dict>
		<key>name-scope</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.other.name.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(- name)(\2))(:) +((["']?).*?(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.name-main.yaml-tmtheme</string>
		</dict>
		<key>scope</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.other.name.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(  scope)(\2))(:) +((["']?).*?(\7))(?=,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.scope.yaml-tmtheme</string>
		</dict>
		<key>semanticClass</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(semanticClass)(\2))(:) +((["']?).*?(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.semanticClass.yaml-tmtheme</string>
		</dict>
		<key>settings-default</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.settings.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(- settings)(\2))(:)</string>
			<key>name</key>
			<string>meta.settings-default.yaml-tmtheme</string>
		</dict>
		<key>settings-main</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.settings.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(settings)(\2))(:)</string>
			<key>name</key>
			<string>meta.settings-main.yaml-tmtheme</string>
		</dict>
		<key>settings-scope</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.settings.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(  settings)(\2))(:)</string>
			<key>name</key>
			<string>meta.settings-default.yaml-tmtheme</string>
		</dict>
		<key>uuid</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.uuid.yaml-tmtheme</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmtheme</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmtheme</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.uuid.yaml-tmtheme</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmtheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:,|\{ *|^)((["']?)(uuid)(\2))(:) +((["']?)(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})(\7))</string>
			<key>name</key>
			<string>meta.uuid.yaml-tmtheme</string>
		</dict>
		<key>yaml-doc-end</key>
		<dict>
			<key>match</key>
			<string>^\.{3}$</string>
			<key>name</key>
			<string>entity.other.document-end.yaml-tmtheme</string>
		</dict>
		<key>yaml-doc-start</key>
		<dict>
			<key>match</key>
			<string>^---(?= |$)</string>
			<key>name</key>
			<string>entity.other.document-start.yaml-tmtheme</string>
		</dict>
		<key>yaml-tab-error</key>
		<dict>
			<key>match</key>
			<string>^\t+</string>
			<key>name</key>
			<string>invalid.illegal.tab-indent.yaml-tmtheme</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.yaml-tmtheme</string>
	<key>uuid</key>
	<string>a3cebb90-80fe-11e3-baa7-0800200c9a66</string>
</dict>
</plist>
