<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>YAML-tmLanguage</string>
	</array>
	<key>name</key>
	<string>Sublime Text Syntax Def (YAML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^---(?= |$)</string>
			<key>name</key>
			<string>entity.other.document-start.yaml-tmlanguage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.{3}$</string>
			<key>name</key>
			<string>entity.other.document-end.yaml-tmlanguage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\t+</string>
			<key>name</key>
			<string>invalid.illegal.tab-indent.yaml-tmlanguage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#repository</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#uuid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#name-main</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scope-name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#file-types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#folding-markers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#patterns</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#captures</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#match</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-from-key</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number-key</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#repository-key-inline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unmatched</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>captures</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.captures.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:, +|\{ *|^ {2,}|^ *- +)((["']?)((?:(?:begin|end)C|c)aptures)(\2))(:)</string>
			<key>name</key>
			<string>meta.captures.yaml-tmlanguage</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)((#).*)</string>
		</dict>
		<key>comment-from-key</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^( *)(?:- +)?((["']?)(comment)(\3))(:) +([|&gt;])(?=, |,$| +#| *$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.comment-from-key.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.block.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>block
comment
</string>
					<key>contentName</key>
					<string>comment.block.from-key.block.yaml-tmlanguage</string>
					<key>end</key>
					<string>^(?! *$|\1 )</string>
					<key>name</key>
					<string>meta.comment-from-key.block.yaml-tmlanguage</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^ *|^ *- +)((["']?)(comment)(\2))(:) +(?!#)(["'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.comment-from-key.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>test comment over multiple lines?</string>
					<key>contentName</key>
					<string>comment.block.from-key.quoted.yaml-tmlanguage</string>
					<key>end</key>
					<string>(?&lt;![^\\]\\)(\6)(?=, |,$| +#| *$| *})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.comment-from-key.quoted.yaml-tmlanguage</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^( *)(?:-( +))?((["']?)(comment)(\4))(:)[ ]</string>
					<key>beginCaptures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.comment-from-key.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>this is a "test" comment in another line</string>
					<key>contentName</key>
					<string>comment.block.from-key.unquoted.yaml-tmlanguage</string>
					<key>end</key>
					<string>^(?! *$|\1\2  )</string>
					<key>name</key>
					<string>meta.comment-from-key.unquoted.yaml-tmlanguage</string>
				</dict>
			</array>
		</dict>
		<key>file-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^)((["']?)(fileTypes)(\2))(:) (\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.control.list.opening-bracket.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.list.closing-bracket.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.file-types.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.yaml-tmlanguage</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>support.other.file-types.item.yaml-tmlanguage</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.yaml-tmlanguage</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?:\G|^),? *((["']?)([-\w\._]+)(\2))(?=, |,$| +#| *\Z| *\])</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^)((["']?)(fileTypes)(\2))(:)(?= +#| *$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!$|-| *#)</string>
					<key>name</key>
					<string>meta.file-types.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.yaml-tmlanguage</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>support.other.file-types.item.yaml-tmlanguage</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.yaml-tmlanguage</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^- +((["']?)([-\w\. _]+)(\2))(?= +#| *$)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>folding-markers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^( *)?(?:- +)?((["']?)(author|bundleUUID|firstLineMatch|foldingStartMarker|foldingStopMarker|keyEquivalent)(\3))(:) +([|&gt;])(?=, |,$| +#| *$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.folding-marker.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.block.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.value.yaml-tmlanguage</string>
					<key>end</key>
					<string>^(?! *$|\1 )</string>
					<key>name</key>
					<string>meta.folding-marker.block.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.oniregexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^ {2,}|^ *- +)?((["']?)(author|bundleUUID|firstLineMatch|foldingStartMarker|foldingStopMarker|keyEquivalent)(\2))(:) +(["'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.folding-marker.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.value.yaml-tmlanguage</string>
					<key>end</key>
					<string>\6(?!\6)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.folding-marker.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>''</string>
							<key>name</key>
							<string>test</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.oniregexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^ {2,}|^ *- +)?((["']?)(author|bundleUUID|firstLineMatch|foldingStartMarker|foldingStopMarker|keyEquivalent)(\2))(:) +(?!["'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.folding-marker.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.value.yaml-tmlanguage</string>
					<key>end</key>
					<string>(?=, |,$| +[#{\['"]| *$| *})</string>
					<key>name</key>
					<string>meta.folding-marker.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.oniregexp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.yaml-tmlanguage</string>
		</dict>
		<key>include</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.self-include.yaml-tmlanguage</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>variable.other.include.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.include.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.value.yaml-tmlanguage string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.self-include.yaml-tmlanguage</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>variable.other.include.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)
(?:,\ +|\{\ *|^\ {2,}|^\ *-\ +)
  ((["']?)(include)(\2))(:)\ +
((["'])(?:(\$self)
       |\#?([-\w\.\ ]*)) (\7)
|(\$self)
|([-\w\.\ ]*)
)
</string>
			<key>name</key>
			<string>meta.include.yaml-tmlanguage</string>
		</dict>
		<key>match</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^( *)(?:- +)?((["']?)(match|begin|end)(\3))(:) +([|&gt;])(?=, |,$| +#| *$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.match.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.block.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.value.yaml-tmlanguage</string>
					<key>end</key>
					<string>^(?! *$|\1 )</string>
					<key>name</key>
					<string>meta.match.block.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.oniregexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^ {2,}|^ *- +)((["']?)(match|begin|end)(\2))(:) +(["'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.match.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.value.yaml-tmlanguage</string>
					<key>end</key>
					<string>\6(?!\6)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.match.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>''</string>
							<key>name</key>
							<string>test</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.oniregexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:, +|\{ *|^ {2,}|^ *- +)((["']?)(match|begin|end)(\2))(:) +(?!["'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.match.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.value.yaml-tmlanguage</string>
					<key>end</key>
					<string>(?=, |,$| +[#{\['"]| *$| *})</string>
					<key>name</key>
					<string>meta.match.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.oniregexp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.value.yaml-tmlanguage string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:, +|\{ *|^ {2,}|^ *- +)((["']?)(contentName|name)(\2))(:) +((["']?)[-\w\. ]*(\7))</string>
			<key>name</key>
			<string>meta.name.yaml-tmlanguage</string>
		</dict>
		<key>name-main</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.name.yaml-tmlanguage</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((["']?)(name)(\2))(:) +((["']?).*?(\7))(?=, |,$| +#| *$| *})</string>
			<key>name</key>
			<string>meta.name-main.yaml-tmlanguage</string>
		</dict>
		<key>number-key</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.key.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:, +|\{ *|^ *)((["'])(\d+)(\2))(:)</string>
			<key>name</key>
			<string>meta.number-key.yaml-tmlanguage</string>
		</dict>
		<key>patterns</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.patterns.patterns.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:, +|\{ *|^ *|^ *- +)((["']?)(patterns)(\2))(:)</string>
			<key>name</key>
			<string>meta.patterns.yaml-tmlanguage</string>
		</dict>
		<key>repository</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.repository.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:, +|\{ *)((["']?)(repository)(\2))(:)</string>
					<key>name</key>
					<string>meta.repository.yaml-tmlanguage</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^((["']?)(repository)(\2))(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.repository.yaml-tmlanguage</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml-tmlanguage</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.yaml-tmlanguage</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!\s*($|#))(?=\S)</string>
					<key>name</key>
					<string>meta.repository-block.yaml-tmlanguage</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#repository-key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#captures</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#name</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#match</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#include</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment-from-key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number-key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#unmatched</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>repository-key</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.repository-key.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^  )((["']?)([-\w]+)(\2))(:)</string>
			<key>name</key>
			<string>meta.repository-key.yaml-tmlanguage</string>
		</dict>
		<key>repository-key-inline</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.repository-key.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:, +|\{ *)((["']?)([-\w]+)(\2))(:)</string>
			<key>name</key>
			<string>meta.repository-key.yaml-tmlanguage</string>
		</dict>
		<key>scope-name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.value.yaml-tmlanguage string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:,|\{ *|^)((["']?)(scopeName)(\2))(:) +((["']?)[-\w\. ]*(\7))</string>
			<key>name</key>
			<string>meta.scope-name.yaml-tmlanguage</string>
		</dict>
		<key>unmatched</key>
		<dict>
			<key>match</key>
			<string>^ *- |,(?= *$| +#)</string>
		</dict>
		<key>uuid</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.quoted-or-unquoted.yaml-tmlanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.uuid.yaml-tmlanguage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.yaml-tmlanguage</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.uuid.yaml-tmlanguage</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:,|\{ *|^)((["']?)(uuid)(\2))(:) +((["']?)(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})(\7))</string>
			<key>name</key>
			<string>meta.uuid.yaml-tmlanguage</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.yaml-tmlanguage</string>
	<key>uuid</key>
	<string>112dad9d-558e-4ab2-a4cc-c5f1ffa80ee6</string>
</dict>
</plist>
