name: Syntax Tests

on:
  push:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  main:
    name: Syntax Tests (${{ matrix.build }}, ${{ matrix.packages }})
    strategy:
      matrix:
        include:
          # latest stable build
          - build: stable
            packages: binary
            continue_on_error: false
          # latest dev build
          - build: latest
            packages: binary
            continue_on_error: false
          # earliest build supported by the current release branch
          # note: binary for 4135 does not exist, so we go one higher
          - build: 4136
            packages: v4136
            continue_on_error: false
          # last dev & Packages `master` (may fail)
          - build: latest
            packages: master
            continue_on_error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: SublimeText/syntax-test-action@v2.5.1
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.packages }}
        # On the step level, this does not cause the entire job to fail
        # and thus mark PRs as failing when only one of our tests failed.
        # See also https://github.com/github/feedback/discussions/15452.
        continue-on-error: ${{ matrix.continue_on_error }}
