name: Lint

on:
  push:
    branch: master
    paths:
      - '.github/workflows/typecheck.yml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/typecheck.yml'
      - '**.py'

jobs:
  ty:
    name: Ty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - run: uv run ty check .
